name: Suggest a Coworking Space
description: Suggest a new coworking spot in Leuven
title: "[New Space]: "
labels: ["new-space"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new coworking space! Please fill in as much detail as you can.

  # Basic Info
  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the place
      placeholder: e.g., Coffee & Code
    validations:
      required: true

  - type: input
    id: address
    attributes:
      label: Address
      description: Full address (e.g., "Tiensestraat 38, 3000 Leuven")
      placeholder: e.g., Naamsestraat 49, 3000 Leuven
    validations:
      required: true

  - type: input
    id: google-maps
    attributes:
      label: Google Maps Link
      description: Link to the location on Google Maps (required - we'll extract coordinates from this)
      placeholder: https://maps.google.com/?q=...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: General description of the space
      placeholder: e.g., Staff are laptop-friendly, no time limits. Great natural light.

  - type: input
    id: opening-hours
    attributes:
      label: Opening Hours
      description: When is it open?
      placeholder: e.g., Mon-Fri 08:30-18:00, Sat 09:00-17:00

  # Noise & Atmosphere
  - type: dropdown
    id: noise-level
    attributes:
      label: Noise Level
      description: How noisy is it typically?
      options:
        - Quiet
        - Medium
        - Loud
        - Not sure
    validations:
      required: true

  - type: textarea
    id: atmosphere-notes
    attributes:
      label: Atmosphere Notes
      description: Describe the vibe/feeling/noise level in more detail
      placeholder: e.g., Cozy and quiet, great for focused work. Background jazz music, can get busy at lunch

  # WiFi
  - type: dropdown
    id: wifi-speed
    attributes:
      label: WiFi Speed
      description: How fast is the WiFi?
      options:
        - Fast (100+ Mbps)
        - Medium (20-100 Mbps)
        - Slow (< 20 Mbps)
        - Not sure
    validations:
      required: true

  - type: input
    id: wifi-notes
    attributes:
      label: WiFi Notes
      description: Specific speed test results if you have them
      placeholder: e.g., 150 Mbps down, 50 Mbps up

  # Climate
  - type: dropdown
    id: has-ac
    attributes:
      label: Air Conditioning
      description: Does it have AC?
      options:
        - "Yes"
        - "No"
        - Not sure
    validations:
      required: true

  - type: input
    id: climate-notes
    attributes:
      label: Climate Notes
      description: Notes about heating/cooling/AC
      placeholder: e.g., Good AC in summer, can be cold near the door

  # Food & Drinks
  - type: dropdown
    id: food-availability
    attributes:
      label: Food & Drink Availability
      description: What food and drink options are available?
      options:
        - Full menu
        - Light food/snacks
        - No food
        - Not sure
    validations:
      required: true

  - type: input
    id: food-notes
    attributes:
      label: Food Notes
      description: More details about food options
      placeholder: e.g., Great pastries, lunch served 11am-3pm

  - type: input
    id: drink-notes
    attributes:
      label: Drink Notes
      description: What drinks do they serve?
      placeholder: e.g., Coffee, tea, fresh juices

  # Seating
  - type: dropdown
    id: seating-type
    attributes:
      label: Seating Type
      description: What kind of seating is available?
      options:
        - Individual tables (small, 1-2 person)
        - Mixed (various table sizes)
        - Group tables (large shared tables)
        - Not sure
    validations:
      required: true

  - type: input
    id: seating-notes
    attributes:
      label: Seating Notes
      description: Describe the seating and layout
      placeholder: e.g., 10 person communal table near the window, plus smaller 2-person tables

  # Power Outlets
  - type: dropdown
    id: outlets
    attributes:
      label: Power Outlets
      description: How many power outlets are available?
      options:
        - Many outlets
        - Some outlets
        - Few outlets
        - Not sure
    validations:
      required: true

  - type: input
    id: outlet-notes
    attributes:
      label: Outlet Notes
      description: Details about power outlet locations and availability
      placeholder: e.g., Outlets at most tables, some near the windows
